class DataIngestionArtifact:
    pass


class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTraingArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...